"""add_goal_entry

Revision ID: d95d09890949
Revises: b479dd0a6de9
Create Date: 2026-01-01 23:38:11.618277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd95d09890949'
down_revision: Union[str, None] = 'b479dd0a6de9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('goal_text', sa.String(), nullable=False),
    sa.Column('target_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('is_completed', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goal_entries')
    # ### end Alembic commands ###
